### ISSUE TITLE
Model for DJ seat

### ISSUE THREAD

**Issue by kowalski** [turntablefm/turntable#19]
DJ seats are resources for which users will compete.
We need to model one seat (we will have 5 instances of this model).

We need to store information:
* who is occupying the seat (or null - empty)
* nonce of the seat state (integer number)

When you want to occupy the seat you send a message including:
* `nonce + 1` of the state you are referencing 
* which seat you want to take (or release)
* timestamp
* hash of parameters (important bit!)

When we receive a message to take a seat we allow it when:
* nonce of the message is higher than the nonce of the seat
* if nonce of the seat is equal to nonce of the message we compare the hashes
 * whichever hash is lower alphabetically (`"cat" < "dog"`) wins 

I know this is easy to hack when given the ability to forge messages, but this is good enough for now.

**Comment by JaHajRF** [comment]
Issue continuation -> #45
